### ISSUE TITLE
feat: Channel

### ISSUE THREAD

**Issue by ChangHoon-Sung** [KMUCS23-RUST-A/raingame-rs#3]
<img width="300" alt="ScreenShot 2023-04-27 at 00 30 40@2x" src="https://user-images.githubusercontent.com/37946887/234625860-f31a1ef3-6bf7-42c1-8380-0291ebe63a6b.png">

엔드-투-엔드 이벤트 전달을 위해 서버 파트에서 핸들러 쓰레드 간 정보 전달이 필요하다.

여기서 Rust의 기능으로 `channel`을 사용하면 쓰레드 간 메세지 전달을 구현할 수 있다.
channel은 목적에 따라 다양한 구현체를 사용할 수 있다.

Producer/Consumer 관계별 구현체
- 1:1 (`oneshot`, tokio) - 딱 1개의 메세지만 전달함
- 1:N (`watch`, tokio)
- N:1 (`mpsc`, std & tokio)
- N:M (`broadcast`, tokio)

### Todo

- [x] 서버 channel 구현
- [x] Ncurses 쓰레드 포팅
- [x] 클라이언트 channel 구현

### 참고 자료
- https://tokio.rs/tokio/tutorial/channels
- https://doc.rust-lang.org/std/sync/mpsc/index.html

**Comment by ChangHoon-Sung** [comment]
@Binsk-dev oneshot 테스트 결과, 말 그대로 딱 하나의 메세지만 전달하고 채널이 닫히는 것  같더군요. mpsc로 변경하고, producer를 하나만 사용하는 방식으로 구현하려고 합니다.
